import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import './globals.css'

import { ThemeProvider } from 'next-themes'
import { Nunito } from 'next/font/google'
import { Toaster } from 'sonner'

const fontNunito = Nunito({
    subsets: ['latin'],
    variable: '--nunito',
    weight: ['200', '300', '400', '500', '700', '800'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body
                className={cn(
                    'min-h-screen bg-slate-800 font-nunito antialiased',
                    fontNunito.variable,
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                    <Toaster richColors position='top-right'/>
                </ThemeProvider>
            </body>
        </html>
    )
}
