import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import './globals.css'

import { Providers } from '@/providers'
import { } from '@radix-ui/react-tooltip'
import { Nunito } from 'next/font/google'

const fontNunito = Nunito({
    subsets: ['latin'],
    variable: '--nunito',
    weight: ['200', '300', '400', '500', '700', '800'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode

}>) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body
                className={cn(
                    'min-h-screen bg-slate-800 font-nunito antialiased',
                    fontNunito.variable,
                )}
            >
                <>
                    <Providers>
                        {children}
                    </Providers>
                </>
            </body>
        </html>
    )
}
