import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";

import { Nunito } from 'next/font/google';
const fontNunito = Nunito({
    subsets: ['latin'],
    variable: '--nunito',
    weight: ['200', '300', '400', '500', '700', '800'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
          <body
              className={cn(
                  'min-h-screen bg-slate-800 font-nunito antialiased',
                  fontNunito.variable,
              )}
          >
              {children}
          </body>
      </html>
  )
}
