import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Página | Login',
    description: 'Generated by create next app',
}

export default function PageSigninLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
     return (
         <div className="min-h-screen bg-slate-800 font-nunito antialiased">
             <main>{children}</main>
         </div>
     )
}
