import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Página | Registro',
    description: 'Generated by create next app',
}

export default function PageSignupLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <div className="min-h-screen bg-slate-800 font-nunito antialiased rounded-sm">
            <main>{children}</main>
        </div>
    )
}
