import { cn } from '@/lib/utils'
import type { Metadata } from 'next'

import { Nunito } from 'next/font/google'
const fontNunito = Nunito({
    subsets: ['latin'],
    variable: '--nunito',
    weight: ['200', '300', '400', '500', '700', '800'],
})

export const metadata: Metadata = {
    title: 'Página | Registro',
    description: 'Generated by create next app',
}

export default function PageSignupLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    'min-h-screen bg-slate-800 font-nunito antialiased',
                    fontNunito.variable,
                )}
            >
                {children}
            </body>
        </html>
    )
}
